version: "3"

services:

  ladder:
    image: oraladder/ladder:mariadb
    environment:
      FLASK_LADDER_BANS_FILE: "/home/openra/banned_profiles"
      FLASK_LADDER_API_KEY: apitest
      FLASK_LADDER_MAIN_DATABASE: "mariadb+mariadbconnector://ladder:ladderdbsecret@database:3306/ladder"
    ports:
      - "8000:8000"

  database:
    image: mariadb:11
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ladderdevdbroot
      MARIADB_DATABASE: ladder
      MARIADB_USER: ladder
      MARIADB_PASSWORD: ladderdbsecret
    ports:
      - 127.0.0.1:3306:3306

volumes:
  mariadb_data:
